// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

// Discovery's start and the manifest heartbeat run here, on the isolate that
// owns them — the UI isolate, in the products. The avoid_slow_async_io lint
// prefers the *Sync() calls, which hold that isolate for the whole system
// call; this file stays on the asynchronous API so it never does.
// ignore_for_file: avoid_slow_async_io

import 'dart:async';
import 'dart:io';

import 'package:crux_cxp/src/cxp_file_mode.dart';
import 'package:meta/meta.dart';
import 'package:path/path.dart' as p;

/// `rwx------`: what CXP §10.1 asks of a directory a peer creates on the
/// manifest path.
const int cxpOwnerOnlyDirectoryMode = 0x1c0;

/// `rw-------`: what CXP §10.2 asks of a manifest, which carries a token.
const int cxpOwnerOnlyFileMode = 0x180;

/// The group and other permission bits — anything here is readable,
/// writable or searchable by someone who is not the owner.
const int _groupOrOtherBits = 0x3f;

/// Creates [path] if it does not exist, owner-only, and tightens it to
/// owner-only if it does.
///
/// Since wire 1.2 the manifest directory holds every local peer's token
/// (§10.1), and a token proves file access only if other users cannot read
/// it. `Directory.create` makes directories with the process umask — `0755`
/// under the usual `022` — so on a Linux system whose home directories are
/// themselves `0755`, every local user could list and read the manifests.
///
/// - Each directory this call creates, from the deepest existing ancestor
///   down, is made `0700`. Ancestors that already existed are left alone:
///   they are the user's, not this protocol's.
/// - [path] itself is made `0700` whoever created it, when it grants any
///   access to group or others — an older build, or a product that created
///   it with default permissions, leaves it `0755`.
///
/// POSIX only. On Windows `%APPDATA%` lives in the user's profile, whose
/// access-control list already admits only that user (and SYSTEM and the
/// administrators, who can read every file anyway), and a directory made
/// there inherits that list; nothing is changed. Setting a mode is best
/// effort: a filesystem without modes, or a directory owned by another
/// user, keeps what it has, and the manifest is still written.
Future<void> ensureCxpPrivateDirectory(String path) async {
  final target = p.normalize(p.absolute(path));
  final missing = <String>[];
  var current = target;
  while (!await Directory(current).exists()) {
    missing.insert(0, current);
    final parent = p.dirname(current);
    if (parent == current) break;
    current = parent;
  }
  for (final directory in missing) {
    // One level at a time, so every directory created here is known and
    // gets the mode. A concurrent creator — another product starting at
    // the same moment — is harmless: `create` on an existing directory
    // succeeds, and the mode is set either way.
    await Directory(directory).create();
    if (!Platform.isWindows) {
      setPosixFileMode(directory, cxpOwnerOnlyDirectoryMode);
    }
  }
  if (Platform.isWindows) return;
  final mode = (await FileStat.stat(target)).mode;
  if (mode & _groupOrOtherBits != 0) {
    setPosixFileMode(target, cxpOwnerOnlyDirectoryMode);
  }
}

/// Monotonic discriminator for temporary file names, so two overlapping
/// writes to one destination never share a scratch file.
int _tempCounter = 0;

/// Replaces [file] atomically with [contents], owner-only on POSIX.
///
/// The bytes go to `<file>.<micros>-<counter>.tmp` in the same directory —
/// the naming `crux_io`'s atomic writer uses, which `CxpDiscovery`'s
/// orphan sweep recognises — and are then renamed over [file], so a
/// scanner sees the whole old manifest or the whole new one (§10.2). The
/// scratch file is created exclusively (so a name planted in advance is
/// never followed) and made `0600` while it is still empty; only then is
/// the token written into it, so wherever a mode can be set, no file others
/// can read ever holds the token, not even for the instant before the
/// rename, and the rename keeps the mode. Setting the mode is best effort,
/// as in [ensureCxpPrivateDirectory].
///
/// No `fsync`: a manifest is discovery state, republished every heartbeat,
/// and one lost to a crash is regenerated by a process that had to restart
/// anyway (`crux_io`'s `WriteDurability.ephemeral` reasoning).
///
/// On failure the scratch file is removed, best effort, and the error is
/// rethrown. [onBeforeWrite] and [onBeforeRename] are test seams fired with
/// the scratch file just before [contents] is written into it and just
/// before it is renamed.
Future<void> writeCxpPrivateFileAtomic(
  File file,
  String contents, {
  @visibleForTesting FutureOr<void> Function(File scratch)? onBeforeWrite,
  @visibleForTesting FutureOr<void> Function(File scratch)? onBeforeRename,
}) async {
  final stamp = DateTime.now().microsecondsSinceEpoch;
  final scratch = File('${file.path}.$stamp-${_tempCounter++}.tmp');
  try {
    await scratch.create(exclusive: true);
    if (!Platform.isWindows) {
      setPosixFileMode(scratch.path, cxpOwnerOnlyFileMode);
    }
    if (onBeforeWrite != null) await onBeforeWrite(scratch);
    await scratch.writeAsString(contents);
    if (onBeforeRename != null) await onBeforeRename(scratch);
    await scratch.rename(file.path);
  } on Object {
    try {
      if (scratch.existsSync()) await scratch.delete();
    } on FileSystemException {
      // An orphaned scratch file is swept by discovery; the write failure
      // is the error the caller needs to see.
    }
    rethrow;
  }
}
