// Copyright 2026 Ferrite Engineering LLC
// SPDX-License-Identifier: Apache-2.0

import 'package:crux_netlist/crux_netlist.dart' show Module;
import 'package:crux_netlist/src/bit_ref.dart';
import 'package:crux_netlist/src/module.dart' show Module;
import 'package:crux_netlist/src/port_direction.dart';
import 'package:meta/meta.dart';

/// A cell instance inside a [Module]: a logic primitive (`$and`, `$mux`),
/// a flip-flop (`$dff`), or a user-defined module instantiated by name.
///
/// Connections map each named port of the cell to the bits driving / driven
/// by that port, in LSB-first order. [portDirections] mirrors the keyset of
/// [connections] and gives the direction of each port — Yosys may emit it
/// or omit it depending on whether the cell type was elaborated against a
/// known interface.
@immutable
class Cell {
  /// Creates a cell instance.
  const Cell({
    required this.name,
    required this.type,
    required this.parameters,
    required this.attributes,
    required this.portDirections,
    required this.connections,
    this.hideName = false,
  });

  /// Parses a cell from the JSON shape Yosys writes under
  /// `modules.<m>.cells.<name>`.
  factory Cell.fromJson(String name, Map<String, Object?> json) {
    final type = json['type']! as String;
    final hideName = (json['hide_name'] as int? ?? 0) != 0;
    final parameters = _readStringMap(json['parameters']);
    final attributes = _readStringMap(json['attributes']);
    final portDirsRaw =
        json['port_directions'] as Map<String, Object?>? ?? const {};
    final portDirections = <String, PortDirection>{
      for (final entry in portDirsRaw.entries)
        entry.key: PortDirection.fromJson(entry.value! as String),
    };
    final connectionsRaw =
        json['connections'] as Map<String, Object?>? ?? const {};
    final connections = <String, List<BitRef>>{
      for (final entry in connectionsRaw.entries)
        entry.key: <BitRef>[
          for (final bit in entry.value! as List<Object?>) BitRef.fromJson(bit),
        ],
    };
    return Cell(
      name: name,
      type: type,
      parameters: parameters,
      attributes: attributes,
      portDirections: portDirections,
      connections: connections,
      hideName: hideName,
    );
  }

  /// Cell instance name as written in the source (or auto-generated by
  /// Yosys when [hideName] is true).
  final String name;

  /// Cell type — either a Yosys primitive (`$and`, `$mux`, `$dff`, …) or a
  /// user-defined module name.
  final String type;

  /// Cell parameters (parametric module instantiation arguments). Values
  /// are kept as raw strings because Yosys may emit binary literals,
  /// integers, or quoted strings; consumers know the expected type.
  final Map<String, String> parameters;

  /// Source attributes attached to the cell (e.g. `src`, `keep`).
  final Map<String, String> attributes;

  /// Per-port direction. Keys must match the keyset of [connections].
  final Map<String, PortDirection> portDirections;

  /// Per-port bit lists. Bits are in LSB-first order.
  final Map<String, List<BitRef>> connections;

  /// Whether Yosys generated an auto-name for this cell (true) or the cell
  /// has a name from the source HDL (false).
  final bool hideName;

  /// Returns a copy with the given fields replaced.
  Cell copyWith({
    String? name,
    String? type,
    Map<String, String>? parameters,
    Map<String, String>? attributes,
    Map<String, PortDirection>? portDirections,
    Map<String, List<BitRef>>? connections,
    bool? hideName,
  }) {
    return Cell(
      name: name ?? this.name,
      type: type ?? this.type,
      parameters: parameters ?? this.parameters,
      attributes: attributes ?? this.attributes,
      portDirections: portDirections ?? this.portDirections,
      connections: connections ?? this.connections,
      hideName: hideName ?? this.hideName,
    );
  }

  /// Yosys-compatible JSON map. Does not include the cell's name (that key
  /// lives one level up in the enclosing map).
  Map<String, Object?> toJson() => <String, Object?>{
    'hide_name': hideName ? 1 : 0,
    'type': type,
    'parameters': parameters,
    'attributes': attributes,
    'port_directions': <String, Object?>{
      for (final entry in portDirections.entries)
        entry.key: entry.value.toJsonString(),
    },
    'connections': <String, Object?>{
      for (final entry in connections.entries)
        entry.key: <Object>[for (final bit in entry.value) bit.toJson()],
    },
  };

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! Cell) return false;
    if (other.name != name) return false;
    if (other.type != type) return false;
    if (other.hideName != hideName) return false;
    if (!_mapEquals(other.parameters, parameters)) return false;
    if (!_mapEquals(other.attributes, attributes)) return false;
    if (!_mapEquals(other.portDirections, portDirections)) return false;
    if (other.connections.length != connections.length) return false;
    for (final entry in connections.entries) {
      final otherBits = other.connections[entry.key];
      if (otherBits == null) return false;
      if (otherBits.length != entry.value.length) return false;
      for (var i = 0; i < entry.value.length; i++) {
        if (otherBits[i] != entry.value[i]) return false;
      }
    }
    return true;
  }

  @override
  int get hashCode => Object.hash(
    name,
    type,
    hideName,
    _mapHash(parameters),
    _mapHash(attributes),
    _mapHash(portDirections),
    _connectionsHash(connections),
  );

  @override
  String toString() => 'Cell(name: $name, type: $type)';
}

Map<String, String> _readStringMap(Object? value) {
  if (value is! Map<String, Object?>) return const <String, String>{};
  return <String, String>{
    for (final entry in value.entries) entry.key: entry.value?.toString() ?? '',
  };
}

bool _mapEquals<K, V>(Map<K, V> a, Map<K, V> b) {
  if (a.length != b.length) return false;
  for (final entry in a.entries) {
    if (!b.containsKey(entry.key)) return false;
    if (b[entry.key] != entry.value) return false;
  }
  return true;
}

int _mapHash<K, V>(Map<K, V> map) {
  var hash = 0;
  for (final entry in map.entries) {
    hash ^= Object.hash(entry.key, entry.value);
  }
  return hash;
}

int _connectionsHash(Map<String, List<BitRef>> connections) {
  var hash = 0;
  for (final entry in connections.entries) {
    hash ^= Object.hash(entry.key, Object.hashAll(entry.value));
  }
  return hash;
}
